name: Deploy to Live Channel

on:
  release:
    types: [published]

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    if: github.event.release.draft == false 
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
            node-version: 'lts/*'
            cache: 'yarn'
      
      - name: 'Install Node Packages'
        run: yarn install
        
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
      
      - name: Build Android 
        run: cd android && ./gradlew assembleRelease --no-daemon
        
  add_file_apk_to_release:
    needs: build_apk
    runs-on: ubuntu-latest
    if: github.event.release.draft == false 
    steps:
      - uses: actions/checkout@v2
        
      - name: Update Files On Release
        run: gh release upload $TAG $FILE_PATH
        env:   
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
          FILE_PATH: "./android/app/build/outputs/apk/release/app-release.apk#Apk"
            
